---
title       : "What is `SpaDES`?"
author      : "Alex M Chubaty & Eliot McIntire"
date        : "September 14, 2016"
output      : slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(cache = TRUE)
```

## 5 examples we will look at
 
- [The 3 demo modules in the SpaDES as a model package](https://github.com/PredictiveEcology/SpaDES/blob/master/inst/sampleModules/SpaDES_sampleModules/SpaDES_sampleModules.Rmd)  
  
    - Or singly:  
        
        - [caribouMovement](https://github.com/PredictiveEcology/SpaDES/blob/master/inst/sampleModules/caribouMovement/caribouMovement.R)  
        - [fireSpread](https://github.com/PredictiveEcology/SpaDES/blob/master/inst/sampleModules/fireSpread/fireSpread.R)  
        - [randomLandscapes](https://github.com/PredictiveEcology/SpaDES/blob/master/inst/sampleModules/randomLandscapes/randomLandscapes.R)  
            
- [LCC2005 model ("Land Cover Classification 2005")](http://htmlpreview.github.io/?https://github.com/PredictiveEcology/SpaDES-modules/blob/master/modules/LCC2005/LCC2005.html)
- Vegetation simulation (SpaDES-Landis)
- Agent based models – [wolf IBM](http://htmlpreview.github.io/?https://github.com/PredictiveEcology/SpaDES-modules/blob/master/modules/wolfAlps/wolfAlps.html)
- A shiny app on shinyapps.io (*e.g.*, [Proof of concept](https://spades.shinyapps.io/ForestChange_ProofOfConcept/))
   
## How `SpaDES` works

### Overview

Explain what DES is and how it works; why we want to use it.

## How `SpaDES` works: modules

Lorem ipsum ...

## How `SpaDES` works: events

Lorem ipsum ...

## How `SpaDES` works: data objects

### Input objects

Lorem ipsum ...

### Output objects

Lorem ipsum ...

## How `SpaDES` works: simLists

Explain the `simList` object structure etc.

## Getting started with `SpaDES`

### Model specification

simple examples (using demo modules) of `simInit` and `spades()` calls.

- examine simList structure before and after the `spades()` call

## Getting started with `SpaDES`

### Where to get help

- help files and vignettes
- wiki
- `SpaDES` Users Group

## Getting started with `SpaDES`

### Using pre-built modules

- demo modules included in the package
- `SpaDES` module repository

        downloadModule()
