---
title: "Introduction to ecological modelling with `SpaDES`"
author: "Alex M Chubaty & Eliot McIntire"
output:
  html_document: 
    toc: true
    toc_float: true
    keep_md: true
    number_sections: true
    theme: spacelab
---

This workshop assumes good familiarity with R as well as several of its contributed packages.

# Dates and Times

**Dec 7-9, 2016 [google calendar link](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MzFvcDA5MmI3dDJhMDQxYTE4MzZpZDVuNW8gZWxpb3RtY2ludGlyZUBt&tmsrc=eliotmcintire%40gmail.com)**  
**8:30am - 4:30pm (PDT) each day**  
**Cost: Free**  
**Where: Pacific Forestry Centre, Victoria, BC**  
**WebEx: Limited numbers.** Contact Eliot.McIntire@canada.ca if you would like to participate remotely.  
**Rooms:** **Dilbert Hall**  

# Before the workshop 

**([slides](http://Rpubs.com/PredictiveEcology/SpaDES-intro-00-prerequisites))**

- Set up your laptop
- Set your goals for workshop
- [all workshop material (incomplete until workshop begins), zipped](https://github.com/PredictiveEcology/workshops/raw/master/SpaDES_intro.zip)

# Workshop content 

([raw version of notes available on github](https://github.com/PredictiveEcology/workshops/tree/master/SpaDES_intro))


## `SpaDES` in action 

**(Presenters Eliot and Alex) ([slides](http://Rpubs.com/PredictiveEcology/SpaDES-Intro-01-spades-in-action))([exercises](http://Rpubs.com/PredictiveEcology/SpaDES-Intro-01-exercises))**

- [The demo modules in the `SpaDES` package](https://github.com/PredictiveEcology/SpaDES/blob/master/inst/sampleModules/SpaDES_sampleModules/SpaDES_sampleModules.Rmd)
- [LCC2005 model ("Land Cover Classification 2005")](http://htmlpreview.github.io/?https://github.com/PredictiveEcology/SpaDES-modules/blob/master/modules/LCC2005/LCC2005.html)
- Vegetation simulation (SpaDES-Landis)
- Agent based models – [wolf IBM](http://htmlpreview.github.io/?https://github.com/PredictiveEcology/SpaDES-modules/blob/master/modules/wolfAlps/wolfAlps.html)
- A shiny app on shinyapps.io (*e.g.*, [Proof of concept](https://spades.shinyapps.io/ForestChange_ProofOfConcept/))

## Thinking the `SpaDES` way

**Presenter Eliot ([slides](http://Rpubs.com/PredictiveEcology/SpaDES-Intro-02-thinking-the-spades-way))**

- Events

- Modules

  - Types of `SpaDES` modules:

    - events (*e.g.*, Fire, Vegetation Change)
    - data preparation (*e.g.*, climate data downloading)
    - individual-based modules (*e.g.*, caribou, wolves, mountain pine beetle)
    - parents and children

- Data

## Getting technical 

**Presenter Alex ([slides](http://Rpubs.com/PredictiveEcology/SpaDES-Intro-03-getting-technical))([exercises](http://Rpubs.com/PredictiveEcology/SpaDES-Intro-03-exercises))**
    
a. The parts
    
  - The [simList](http://www.rdocumentation.org/packages/SpaDES/versions/1.3.1/topics/.simList-class)
    
    - Modules
    - Events within modules
    - data
        
  - The [`spades`](http://www.rdocumentation.org/packages/SpaDES/versions/1.3.1/topics/spades) call

    
b. Surface dive
    
  - creating the `simList` ([`simInit()`](http://www.rdocumentation.org/packages/SpaDES/versions/1.3.1/topics/simInit))
  - run model (`spades()`)
  - where to get help
  - using pre-built modules ([`downloadModule`]((http://www.rdocumentation.org/packages/SpaDES/versions/1.3.1/topics/downloadModule)))
        

## Building `SpaDES` modules 

**Presenter Alex ([slides](http://Rpubs.com/PredictiveEcology/SpaDES-Intro-04-modules))([exercises 4 ](http://Rpubs.com/PredictiveEcology/SpaDES-Intro-04-exercises)) ([exercises 4a ](http://Rpubs.com/PredictiveEcology/SpaDES-Intro-04a-exercises))**
    
a. anatomy of a `SpaDES` module
    
b. new module template: [`newModule`](http://www.rdocumentation.org/packages/SpaDES/versions/1.3.1/topics/newModule)
    
c. module metadata [`defineModule`](http://www.rdocumentation.org/packages/SpaDES/versions/1.3.1/topics/defineModule)
    
d. scheduling events: [`scheduleEvent`](http://www.rdocumentation.org/packages/SpaDES/versions/1.3.1/topics/scheduleEvent)
    
e. [`time`](http://www.rdocumentation.org/packages/SpaDES/versions/1.3.1/topics/time)

f. default data sets using `.inputObjects` -->  `?inputs` 
    
f. visualizations: [`Plot`](http://www.rdocumentation.org/packages/SpaDES/versions/1.3.1/topics/Plot)

g. default values for input data sets
    
g. debugging (`spades(sim, debug = TRUE)`)
    
h. [finding SpaDES tools](http://www.rdocumentation.org/packages/SpaDES/versions/1.3.1/topics/spades-package)
    
i. [summary statistics](https://github.com/PredictiveEcology/SpaDES/wiki/Summary-statistics-in-simulations)
    
j. module development checklist

## Simulation experiments and replication 

**Presenter Eliot ([slides](http://Rpubs.com/PredictiveEcology/SpaDES-Intro-05-simulation-experiments-replication))([exercises](http://Rpubs.com/PredictiveEcology/SpaDES-Intro-05-exercises))**
    
a. using the `experiment()` function for replication, scenario creation, and parameter experiments
    
b. running parallel simulations on supercomputers and clusters
    
c. Pattern Oriented Modeling (`POM()` function) for estimating unknown parameters

## Getting the most out of R for ecological models

**Presenters Eliot and Alex ([slides](http://Rpubs.com/PredictiveEcology/SpaDES-Intro-06-getting-most-out-of-r))**

    
a. Spatial data (`raster` and `sp` packages)
    
b. Matrices
    
c. The `data.table` package
    
d. `SpaDES` functions for spreading, moving, neighbourhoods etc. [section 2 of spades-package help file](http://www.rdocumentation.org/packages/SpaDES/versions/1.3.1/topics/spades-package)
    
e. The `Rcpp` package
    
## Module integration

**Presenter Alex ([slides](http://Rpubs.com/PredictiveEcology/SpaDES-Intro-07-module-integration)) ([exercises](http://Rpubs.com/PredictiveEcology/SpaDES-Intro-07-exercises))**
    
a. Building "models", *i.e.*, groups of modules (parents and children)
    
b. Using metadata
    
c. Visual tools: [`objectDiagram`](http://www.rdocumentation.org/packages/SpaDES/versions/1.3.1/topics/objectDiagram), [`moduleDiagram`](http://www.rdocumentation.org/packages/SpaDES/versions/1.3.1/topics/moduleDiagram), [`eventDiagram`](http://www.rdocumentation.org/packages/SpaDES/versions/1.3.1/topics/eventDiagram)

## Sharing modules & models 

**Presenter Alex ([slides](http://Rpubs.com/PredictiveEcology/SpaDES-Intro-08-sharing-modules))([exercises](http://Rpubs.com/PredictiveEcology/SpaDES-Intro-08-exercises))**
    
a. `SpaDES` module repositories
    
b. Using [GitHub.com](https://github.com)
    
c. `shiny` apps and [shinyapps.io](http://www.shinyapps.io/) (*e.g.*, [Proof of concept](https://spades.shinyapps.io/ForestChange_ProofOfConcept/))
    
d. Data sources

## Data to decisions 

**Presenter Eliot
([slides](http://Rpubs.com/PredictiveEcology/SpaDES-Intro-09-workflow))**

a. Building a reproducible workflow
b. Caching

# Resources

- [`SpaDES wiki`](https://github.com/PredictiveEcology/SpaDES/wiki)
- [R documentation for `SpaDES`](http://www.rdocumentation.org/packages/SpaDES/versions/1.3.1)
- [Development release of `SpaDES`](https://github.com/PredictiveEcology/SpaDES/tree/development)
- Link to this [Outline](http://Rpubs.com/PredictiveEcology/SpaDES-Intro-Outline)
- Contact info: Eliot.McIntire@canada.ca or Alexander.Chubaty@canada.ca

# Archived content

Previous versions of this workshop are archived at the links below.

- [2016 Sept 14-16](http://rpubs.com/PredictiveEcology/Archives-Sept16-Outline)

last updated `r Sys.Date()`
